### ISSUE TITLE
Add Simkl Support

### ISSUE THREAD

**Issue by masyk** [Atelier-Shiori/hachidori#23]
Simkl is a TV, Anime, and Movie tracker https://simkl.com. API: https://api.simkl.com has title, ID, filename detection API for implementing Scrobbler for Anime. Dev discord: https://discord.gg/u89XfYn

**Comment by moyitpro** [comment]
May consider it in the future, but not at the moment as the scrobbling engine needs some rewrite to become more modular, making it easier to add support for other Anime only tracking services such as Notify.moe in addition to Simki.

**Comment by moyitpro** [comment]
For the time being, I will not be working on this, but if the second Patreon goal of $20 per month is met, I will work on it. It will be time consuming mostly to implement the API and add support for it to the title id mappings system, which will be used for MultiScrobble (multi-service updates). Since time will be limited, possibly in the future, I will only implement it once the goal is met for this reason.

For the foreseeable future, I will only focus on supporting the most popular anime/manga library tracking services, AniList, Kitsu, MyAnimeList and possibly Anime-Planet when they have an API available.
