### ISSUE TITLE
MAL authorization issue

### ISSUE THREAD

**Issue by TopoR** [Atelier-Shiori/hachidori#42]
Can't authorize to the MAL. Window for credentials, after entering, opens the site.

<img width="644" alt="Screenshot 2020-07-16 at 01 08 59" src="https://user-images.githubusercontent.com/4129779/87605623-cb6c7980-c701-11ea-8e41-1fea77f4be53.png">

**Comment by moyitpro** [comment]
Apparently, it’s a bug on the MyAnimeList side as other app developers in the MyAnimeList developer slack is having the same issue. I will let you know once there is a solution in regard to the redirect issue or when the MyAnimeList api team fixes the issue.

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by moyitpro** [comment]
This may be related:

https://myanimelist.net/forum/?topicid=1852142#msg60219910

**Comment by moyitpro** [comment]
xmil investigated the issue and filed a bug report. Hopefully it will be fixed soon. 

I will add additional buttons such as the back and forward buttons for the web view on the OAuth web view dialog along with the ability to use a web browser to complete the OAuth process for both Hachidori and Shukofukurou for macOS.

**Comment by moyitpro** [comment]
I know MyAnimeList will fix this, but I don't want  to really wait for them to fix it and added a  work around. The dialog will simply reload the OAuth URL so that the user can continue the OAuth process. Also, added the ability for the user to do the OAuth authorization in his or her web browser.

https://github.com/Atelier-Shiori/hachidori/commit/231973a44a8534dc0190f8a091bcec89d0741164

I will have a release with this fix out in a few hours.
