### ISSUE TITLE
Scrobbler isn't updating my list at all since I updated to Big Sur 11.4

### ISSUE THREAD

**Issue by senpyi** [Atelier-Shiori/hachidori#45]
Hi,

I am having an issue where no matter what website I am on (Netflix, Prime etc), the scrobbler isn't updating at all. This wasn't happening before I updated to Big Sur 11.4. Please help me!

**Comment by moyitpro** [comment]
Make sure the Enable Javascript from Apple Events is enabled in Safari/Chrome/Edge from the Develop menu (In Chrome/Edge, it’s in the Tools menu). Otherwise, nothing will detect.

From: senpyi ***@***.***>
Reply-To: Atelier-Shiori/hachidori ***@***.***>
Date: Monday, July 5, 2021 at 5:14 PM
To: Atelier-Shiori/hachidori ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Atelier-Shiori/hachidori] Scrobbler isn't updating my list at all since I updated to Big Sur 11.4 (#45)


Hi,

I am having an issue where no matter what website I am on (Netflix, Prime etc), the scrobbler isn't updating at all. This wasn't happening before I updated to Big Sur 11.4. Please help me!

**Comment by senpyi** [comment]
Hi, so I have checked and Enable Javascript is on for me but I don't know how to check the Automation setting, how do I check that?

**Comment by moyitpro** [comment]
See https://help.malupdaterosx.moe/hachidori/getting-started/

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by senpyi** [comment]
Hi, thank you. Out of curiosity I tried it on my funimation account and it works on there but not on Netflix, is there anything I would need to do to get it to work with Netflix?

**Comment by moyitpro** [comment]
Netflix support might need to be fixed since it’s been a while since I last updated it and I don’t have a current subscription. It’s something I will need to fix in the future

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by senpyi** [comment]
Ah okay that's fair enough! Thank you for all the help :)
