### ISSUE TITLE
Hachidori crashes when scrobbling from Plex web on El Capitan

### ISSUE THREAD

**Issue by nicoNaN** [Atelier-Shiori/hachidori#8]
When Hachidori attempts to scrobble automatically after 5 minutes or by performing a manual update on a show playing in the Plex web app it silently crashes. No "unexpectedly quit" message from OS X whatsoever. I know the changelog includes support for 10.11 so I'm wondering if you can reproduce this issue or if it's simply my configuration. This is also an issue with the MAL scrobbler.

I'm on 10.11.1. I've confirmed this is only happening with Plex web - scrobbling while using mpv works flawlessly.

**Comment by chikorita157** [comment]
Can you copy and paste the crash report. It might have to do with the Keychain implementation since the application works on my side.

**Comment by nicoNaN** [comment]
Here's a link to the crash report: https://gist.github.com/nicoNaN/fdc2ac380cc56f41d6bf

The output from `detectstream` with Plex running in Safari:
```
{"result":[{"title":"One-Punch Man -  ·"},{"title":"One-Punch Man -  ·"}]}
```

Looks like there's no episode number or additional info.

What do you mean by Plex agent exactly? I'm using Agents in Plex to fetch metadata for my media library but I believe that's it. Sorry for my lack of knowledge!

Let me know if there's any additional info I can get you to help debug.

**Comment by chikorita157** [comment]
A plex agent basically gives the metadata to the video file. Normally, we will parse out the title since without the Plex Agent replacing the metadata, we can normally get the show title, episode number and all that good stuff. With a Plex Agent for things like Anime enabled, that data is not accessible and the ones I have heard of does not provide it in the JSON when using the JSON RPC API.

If you are watching a movie, perhaps this can be one of the reason why it won't provide a number, but still.

**Comment by nicoNaN** [comment]
Thanks for the clarification! I'll give it a shot without an agent enabled in Plex.

Do you know if any of the agents provide the data in an alternative format like XML? I'd be interested in extending the functionality of Hachidori to support that, if possible.
